
development:
  adapter: postgresql
  encoding: unicode
  database: sightseeing_development
  pool: 5
  host: localhost
  username: janesternbach
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: sightseeing_test
  pool: 5
  host: localhost
  username: janesternbach
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: sightseeing_production
  pool: 5
  host: localhost
  username: janesternbach
  password:
